server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: campus_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_take_out
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1

campus_take_out:
  storage_path: /Users/baymax/codes/MyCodes/campus_take_out_img/
